#!/usr/bin/env python3
"""Export every Access source table into a PostgreSQL import script.

This is the complete production-data migration path. It intentionally includes
all operational data, guest PII, and old payment-card fields because the target
Supabase/PostgreSQL instance is expected to run on an air-gapped local network.

The exported SQL rewrites mdbtools table targets such as ypl.tblguest to the
renamed production tables such as ypl.guests while preserving all Access column
names and values.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path
from typing import cast

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from supabase.tools.access_table_map import (  # noqa: E402
    SERIAL_COLUMNS,
    TABLES,
    TARGET_SCHEMA,
    rewrite_export_sql,
    sequence_reset_sql,
)

DEFAULT_DB = ROOT / "legacy-db" / "YPLogicCurrentConsolidated.accdb"
DEFAULT_OUTPUT = ROOT / "supabase" / "legacy_import" / "all_legacy_data.sql"


def require_tool(name: str) -> None:
    if shutil.which(name) is None:
        raise SystemExit(f"Required tool not found on PATH: {name}")


def mdb_count(access_db: Path, access_table: str) -> str:
    return subprocess.check_output(
        ["mdb-count", str(access_db), access_table],
        text=True,
        stderr=subprocess.STDOUT,
    ).strip()


def export_insert_sql(access_db: Path, access_table: str) -> str:
    exported = subprocess.check_output(
        [
            "mdb-export",
            "-I",
            "postgres",
            "-N",
            TARGET_SCHEMA,
            "-B",
            "-D",
            "%Y-%m-%d",
            "-T",
            "%Y-%m-%d %H:%M:%S",
            "-b",
            "strip",
            str(access_db),
            access_table,
        ],
        text=True,
        stderr=subprocess.STDOUT,
    )
    return rewrite_export_sql(exported)


def build_import_sql(access_db: Path, include_counts: bool) -> str:
    postgres_tables = [table.postgres_name for table in TABLES]

    parts: list[str] = []
    parts.append(
        "".join(
            [
                "-- =============================================================================\n",
                "-- Complete Access production import\n",
                "-- Generated by supabase/tools/export_access_data.py from\n",
                f"-- {access_db.relative_to(ROOT) if access_db.is_relative_to(ROOT) else access_db}\n",
                "--\n",
                "-- Includes every Access table, including operational guest/reservation data,\n",
                "-- backups/history/helper tables, PII, and old payment-card fields.\n",
                "-- Target tables use Supabase-friendly snake_case names; columns preserve\n",
                "-- mdbtools-normalized Access names for lossless import.\n",
                "-- =============================================================================\n\n",
                f"set search_path = {TARGET_SCHEMA}, public;\n\n",
                "begin;\n",
                "set constraints all deferred;\n",
                "-- Load legacy rows byte-for-byte: business-logic triggers\n",
                "-- (0005_business_logic.sql) must not recompute or validate\n",
                "-- historical data during the import. Requires superuser, which\n",
                "-- the controlled migration environment provides.\n",
                "set session_replication_role = replica;\n\n",
            ]
        )
    )

    truncate_targets = ",\n  ".join(
        f"{TARGET_SCHEMA}.{table}" for table in postgres_tables
    )
    parts.append(f"truncate table\n  {truncate_targets}\nrestart identity cascade;\n\n")

    for table in TABLES:
        count_suffix = (
            f" ({mdb_count(access_db, table.access_name)} rows)"
            if include_counts
            else ""
        )
        parts.append(
            f"-- ---- {table.access_name} -> {TARGET_SCHEMA}.{table.postgres_name}{count_suffix} ----\n"
        )
        exported = export_insert_sql(access_db, table.access_name).strip()
        parts.append((exported if exported else "-- no rows") + "\n\n")

    parts.append("set session_replication_role = default;\n\n")
    parts.append("-- Keep serial sequences ahead of imported Access IDs.\n")
    for table, column in SERIAL_COLUMNS:
        parts.append(sequence_reset_sql(table, column) + "\n")

    parts.append(
        "\n-- Keep in-house reservation numbering ahead of imported data.\n"
        f"select setval('{TARGET_SCHEMA}.resnumber_seq',\n"
        f"  greatest(coalesce((select max(resnumber) from {TARGET_SCHEMA}.reservations), 100000),\n"
        "  100000));\n"
    )
    parts.append("\ncommit;\n")
    return "".join(parts)


def apply_with_psql(output: Path, database_url: str) -> None:
    require_tool("psql")
    _ = subprocess.run(
        ["psql", database_url, "--set", "ON_ERROR_STOP=on", "--file", str(output)],
        check=True,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Export all tables from legacy-db/YPLogicCurrentConsolidated.accdb into "
            f"renamed {TARGET_SCHEMA}.* PostgreSQL tables."
        )
    )
    _ = parser.add_argument(
        "--access-db",
        type=Path,
        default=DEFAULT_DB,
        help=f"Path to the Access .accdb file (default: {DEFAULT_DB.relative_to(ROOT)})",
    )
    _ = parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"SQL file to write (default: {DEFAULT_OUTPUT.relative_to(ROOT)})",
    )
    _ = parser.add_argument(
        "--database-url",
        help="Optional PostgreSQL connection URL. When supplied, run psql against the generated SQL.",
    )
    _ = parser.add_argument(
        "--skip-counts",
        action="store_true",
        help="Do not call mdb-count for row-count comments before exporting each table.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    access_db = cast(Path, args.access_db)
    output = cast(Path, args.output)
    database_url = cast(str | None, args.database_url)
    skip_counts = cast(bool, args.skip_counts)

    require_tool("mdb-export")
    if not skip_counts:
        require_tool("mdb-count")

    if not access_db.exists():
        raise SystemExit(f"Access database not found: {access_db}")

    sql = build_import_sql(access_db, include_counts=not skip_counts)
    output.parent.mkdir(parents=True, exist_ok=True)
    _ = output.write_text(sql)
    print(
        f"Wrote {output.relative_to(ROOT) if output.is_relative_to(ROOT) else output}"
    )

    if database_url:
        apply_with_psql(output, database_url)


if __name__ == "__main__":
    main()
